[package]
name = "firecracker-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
firecracker-api.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
